name: 'Check commit message style'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - feature/*
      - develop
      - main

jobs:
  check-commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v3.0.0
        with:
          max-subject-line-length: '100'
          allow-one-liners: 'true'
          skip-body-check: 'true'
